# Generated by Django 3.2.2 on 2021-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210510_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=75),
            preserve_default=False,
        ),
    ]
